[book]
title = "Optimization Lab"
authors = ["Cory Todd"]
language = "en"
src = "src"

[build]
build-dir = "html"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
git-repository-url = "https://github.com/corytodd/optimization-lab/tree/main/book"
